# -*- coding: utf-8 -*-
"""pythonweek2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W-sTtBua5toOXTfjsiRxtwz4II5xHPCc
"""

#create a variable called price
price = int(input"what is the price of energy drink? "))
#create an other variable that ask user about the quantity of energy
quantity = int(input("what is the quantity of the energy drink do you want to buy?"))
total = price * quantity
print(f"the price of energy drink in USD{price:.2f}")
print(f"the total quantity of the energy drink you want to buy is {quantity}")
print(f"the total price of energy drink is USD {total:.2f}")
#create an other variable that calculates the total of the price and quantity